import {
  CameraOutlined,
  UserOutlined,
  LogoutOutlined,
  SettingOutlined,
  HomeOutlined,
  TeamOutlined,
  PictureOutlined,
  SafetyOutlined,
  MenuOutlined,
  AppstoreOutlined,
  AuditOutlined,
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  SearchOutlined,
  ReloadOutlined,
  UploadOutlined,
  FolderOpenOutlined,
  MailOutlined,
  LockOutlined,
  SaveOutlined,
  BulbOutlined,
  BulbFilled,
  CheckOutlined,
  CloseOutlined,
  ClockCircleOutlined,
  HeartOutlined,
  StarOutlined,
  GlobalOutlined,
  EnvironmentOutlined,
  TagsOutlined,
  FolderOutlined,
  FileImageOutlined,
  PlayCircleOutlined,
  PauseCircleOutlined,
  SoundOutlined,
  VideoCameraOutlined,
  WechatOutlined,
  QqOutlined,
  GithubOutlined,
  AlipayOutlined,
  TaobaoOutlined,
  AndroidOutlined,
  AppleOutlined,
  WindowsOutlined,
  ChromeOutlined,
  FirefoxOutlined,
  EdgeOutlined,
  SafariOutlined,
  IeOutlined,
} from '@ant-design/icons';

export const iconList = [
  { label: '摄影', value: 'CameraOutlined', icon: <CameraOutlined /> },
  { label: '用户', value: 'UserOutlined', icon: <UserOutlined /> },
  { label: '设置', value: 'SettingOutlined', icon: <SettingOutlined /> },
  { label: '首页', value: 'HomeOutlined', icon: <HomeOutlined /> },
  { label: '团队', value: 'TeamOutlined', icon: <TeamOutlined /> },
  { label: '图片', value: 'PictureOutlined', icon: <PictureOutlined /> },
  { label: '安全', value: 'SafetyOutlined', icon: <SafetyOutlined /> },
  { label: '菜单', value: 'MenuOutlined', icon: <MenuOutlined /> },
  { label: '应用', value: 'AppstoreOutlined', icon: <AppstoreOutlined /> },
  { label: '审核', value: 'AuditOutlined', icon: <AuditOutlined /> },
  { label: '新增', value: 'PlusOutlined', icon: <PlusOutlined /> },
  { label: '编辑', value: 'EditOutlined', icon: <EditOutlined /> },
  { label: '删除', value: 'DeleteOutlined', icon: <DeleteOutlined /> },
  { label: '搜索', value: 'SearchOutlined', icon: <SearchOutlined /> },
  { label: '刷新', value: 'ReloadOutlined', icon: <ReloadOutlined /> },
  { label: '上传', value: 'UploadOutlined', icon: <UploadOutlined /> },
  { label: '文件夹', value: 'FolderOpenOutlined', icon: <FolderOpenOutlined /> },
  { label: '邮件', value: 'MailOutlined', icon: <MailOutlined /> },
  { label: '锁', value: 'LockOutlined', icon: <LockOutlined /> },
  { label: '保存', value: 'SaveOutlined', icon: <SaveOutlined /> },
  { label: '收藏', value: 'HeartOutlined', icon: <HeartOutlined /> },
  { label: '星标', value: 'StarOutlined', icon: <StarOutlined /> },
  { label: '全球', value: 'GlobalOutlined', icon: <GlobalOutlined /> },
  { label: '位置', value: 'EnvironmentOutlined', icon: <EnvironmentOutlined /> },
  { label: '标签', value: 'TagsOutlined', icon: <TagsOutlined /> },
  { label: '文件夹2', value: 'FolderOutlined', icon: <FolderOutlined /> },
  { label: '图片2', value: 'FileImageOutlined', icon: <FileImageOutlined /> },
  { label: '播放', value: 'PlayCircleOutlined', icon: <PlayCircleOutlined /> },
  { label: '视频', value: 'VideoCameraOutlined', icon: <VideoCameraOutlined /> },
  { label: '声音', value: 'SoundOutlined', icon: <SoundOutlined /> },
];

export const iconMap = {};
iconList.forEach(item => {
  iconMap[item.value] = item.icon;
});

export const getIcon = (name) => iconMap[name] || null;
